// <auto-generated />
using System;
using AspNetWeek4.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetWeek4.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615141024_AddBookCodeToBooks")]
    partial class AddBookCodeToBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetWeek4.Mvc.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinStock")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            BookCode = "BK001",
                            CategoryId = 1,
                            Genre = "Programming",
                            Isbn = "9780132350884",
                            LastUpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 2,
                            Price = 450000m,
                            PublishedDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Prentice Hall",
                            Stock = 10,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Lock",
                            BookCode = "BK002",
                            CategoryId = 1,
                            Genre = "Programming",
                            Isbn = "9781617294532",
                            LastUpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 2,
                            Price = 650000m,
                            PublishedDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Manning",
                            Stock = 5,
                            Title = "ASP.NET Core in Action"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Joel Grus",
                            BookCode = "BK003",
                            CategoryId = 2,
                            Genre = "Data Science",
                            Isbn = "9781491950496",
                            LastUpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 3,
                            Price = 550000m,
                            PublishedDate = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "O'Reilly Media",
                            Stock = 8,
                            Title = "Data Science from Scratch"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Wes McKinney",
                            BookCode = "BK004",
                            CategoryId = 2,
                            Genre = "Data Science",
                            Isbn = "9781492078006",
                            LastUpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 2,
                            Price = 600000m,
                            PublishedDate = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "O'Reilly Media",
                            Stock = 6,
                            Title = "Python for Data Analysis"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Luciano Ramalho",
                            BookCode = "BK005",
                            CategoryId = 1,
                            Genre = "Programming",
                            Isbn = "9781491901427",
                            LastUpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 1,
                            Price = 700000m,
                            PublishedDate = new DateTime(2015, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "O'Reilly Media",
                            Stock = 4,
                            Title = "Fluent Python"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Jake VanderPlas",
                            BookCode = "BK006",
                            CategoryId = 2,
                            Genre = "Data Science",
                            Isbn = "9781491957660",
                            LastUpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 2,
                            Price = 650000m,
                            PublishedDate = new DateTime(2016, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "O'Reilly Media",
                            Stock = 7,
                            Title = "Python Data Science Handbook"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Bill Wagner",
                            BookCode = "BK007",
                            CategoryId = 1,
                            Genre = "Programming",
                            Isbn = "9781492078005",
                            LastUpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 2,
                            Price = 550000m,
                            PublishedDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Pearson",
                            Stock = 5,
                            Title = "Effective C#"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Foster Provost",
                            BookCode = "BK008",
                            CategoryId = 2,
                            Genre = "Data Science",
                            Isbn = "9781491950296",
                            LastUpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinStock = 2,
                            Price = 600000m,
                            PublishedDate = new DateTime(2013, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "O'Reilly Media",
                            Stock = 6,
                            Title = "Data Science for Business"
                        });
                });

            modelBuilder.Entity("AspNetWeek4.Mvc.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Data Science"
                        });
                });

            modelBuilder.Entity("AspNetWeek4.Mvc.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("AspNetWeek4.Mvc.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", (string)null);
                });

            modelBuilder.Entity("AspNetWeek4.Mvc.Models.Book", b =>
                {
                    b.HasOne("AspNetWeek4.Mvc.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AspNetWeek4.Mvc.Models.SaleItem", b =>
                {
                    b.HasOne("AspNetWeek4.Mvc.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetWeek4.Mvc.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("AspNetWeek4.Mvc.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("AspNetWeek4.Mvc.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
